// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';
import 'package:drift/internal/migrations.dart';

import 'schema_v12.dart' as v12;
import 'schema_v20.dart' as v20;
import 'schema_v21.dart' as v21;

class GeneratedHelper implements SchemaInstantiationHelper {
  @override
  GeneratedDatabase databaseForVersion(QueryExecutor db, int version) {
    switch (version) {
      case 12:
        return v12.DatabaseAtV12(db);
      case 20:
        return v20.DatabaseAtV20(db);
      case 21:
        return v21.DatabaseAtV21(db);
      default:
        throw MissingSchemaException(version, versions);
    }
  }

  static const versions = const [12, 20, 21];
}
